apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-project
  labels:
    app: k8s-deploy
  name: k8s-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-deploy
  strategy: 
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: k8s-deploy
    spec:
      serviceAccountName: k8s-sa
      containers:
      - image: nginx
        name: nginx
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000        
        volumeMounts:
        - name: k8s-secret-volume
          mountPath: /etc/secrets
      volumes: 
      - name: k8s-secret-volume
        secret: 
          secretName: api-key
